<?php

$products = [
        //first product beginning with the first part of phones//
        [
            "id" => "101",
            "name" => "samsungphone0",
            "price" => "999.99",
            "image" => "assets/img/samsungphone0.jpg",
            "imagefront" => "assets/img/samsungphone0voorkant.jpg",
            "imageback" => "assets/img/samsungphone0achterkant.jpg",
            "imageside" => "assets/img/samsungphone0zijkant.jpg",
            "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
            "button" => "add to cart",
            "button2" => "",
            "in_stock" => false
        ],
        [
            "id" => "102",
            "name" => "samsungphone1",
            "price" => "1009.99",
            "image" => "assets/img/samsungphone1.jpg",
            "imagefront" => "assets/img/samsungphone1voorkant.jpg",
            "imageback" => "assets/img/samsungphone1achterkant.jpg",
            "imageside" => "assets/img/samsungphone1zijkant.jpg",
            "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
            "button" => "",
            "button2" => "",
            "in_stock" => false
        ],
        [
            "id" => "103",
            "name" => "samsungphone2",
            "price" => "890.99",
            "image" => "assets/img/samsungphone2.jpg",
            "imagefront" => "assets/img/samsungphone2voorkant.jpg",
            "imageback" => "assets/img/samsungphone2achterkant.jpg",
            "imageside" => "assets/img/samsungphone2zijkant.jpg",
            "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
            "button" => "",
            "button2" => "",
            "in_stock" => true
            
        ],
        [
          "id" => "104",
          "name" => "samsungphone3",
          "price" => "999.99",
          "image" => "assets/img/samsungphone3.jpg",
          "imagefront" => "assets/img/samsungphone3voorkant.jpg",
          "imageback" => "assets/img/samsungphone3achterkant.jpg",
          "imageside" => "assets/img/samsungphone3zijkant.jpg",
          "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
          "button" => "",
          "button2" => "",
          "in_stock" => true
        ],
      //beginning Tv's//
        [
          "id" => "105",
          "name" => "sonytv0",
          "price" => "1009.99",
          "image" => "assets/img/sonytv0.jpg",
          "imagefront" => "assets/img/sonytv0voorkant.jpg",
          "imageback" => "assets/img/sonytv0achterkant.jpg",
          "imageside" => "assets/img/sonytv0zijkant.jpg",
          "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
          "button" => "",
          "button2" => "",
          "in_stock" => true
        ],
        [
          "id" => "106",
          "name" => "sonytv1",
          "price" => "890.99",
          "image" => "assets/img/sonytv1.jpg",
          "imagefront" => "assets/img/sonytv1voorkant.jpg",
          "imageback" => "assets/img/sonytv1achterkant.jpg",
          "imageside" => "assets/img/sonytv1zijkant.jpg",
          "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
          "button" => "",
          "button2" => "",
          "in_stock" => true
          
        ],
       [
        "id" => "107",
        "name" => "samsungtv4",
        "price" => "999.99",
        "image" => "assets/img/samsungtv4.jpg",
        "imagefront" => "assets/img/samsungtv4voorkant.jpg",
        "imageback" => "assets/img/samsungtv4achterkant.jpg",
        "imageside" => "assets/img/samsungtv4zijkant.jpg",
        "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
        "button" => "",
        "button2" => "",
        "in_stock" => true
      ],
      [
        "id" => "108",
        "name" => "samsungtv5",
        "price" => "1009.99",
        "image" => "assets/img/samsungtv5.jpg",
        "imagefront" => "assets/img/samsungtv5voorkant.jpg",
        "imageback" => "assets/img/samsungtv5achterkant.jpg",
        "imageside" => "assets/img/samsungtv5zijkant.jpg",
        "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
        "button" => "",
        "button2" => "",
        "in_stock" => true
      ],
    //Beginning laptops//
      [
        "id" => "109",
        "name" => "lenovolaptop0",
        "price" => "890.99",
        "image" => "assets/img/lenovolaptop0.jpg",
        "imagefront" => "assets/img/lenovolaptop0voorkant.jpg",
        "imageback" => "assets/img/lenovolaptop0achterkant.jpg",
        "imageside" => "assets/img/lenovolaptop0zijkant.jpg",
        "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
        "button" => "",
        "button2" => "",
        "in_stock" => true
        
      ],
      [
      "id" => "110",
      "name" => "lenovolaptop1",
      "price" => "999.99",
      "image" => "assets/img/lenovolaptop1.jpg",
      "imagefront" => "assets/img/lenovolaptop1voorkant.jpg",
      "imageback" => "assets/img/lenovolaptop1achterkant.jpg",
      "imageside" => "assets/img/lenovolaptop1zijkant.jpg",
      "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
      "button" => "",
      "button2" => "",
      "in_stock" => true
    ],
    [
      "id" => "111",
      "name" => "hplaptop2",
      "price" => "1009.99",
      "image" => "assets/img/hplaptop2.jpeg",
      "imagefront" => "assets/img/hplaptop2voorkant.jpg",
      "imageback" => "assets/img/hplaptop2achterkant.jpg",
      "imageside" => "assets/img/hplaptop2zijkant.jpg",
      "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
      "button" => "",
      "button2" => "",
      "in_stock" => true
    ],
    [
      "id" => "112",
      "name" => "hplaptop3",
      "price" => "890.99",
      "image" => "assets/img/hplaptop3.jpg",
      "imagefront" => "assets/img/hplaptop3voorkant.jpg",
      "imageback" => "assets/img/hplaptop3achterkant.jpg",
      "imageside" => "assets/img/hplaptop3zijkant.jpg",
      "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
      "button" => "",
      "button2" => "",
      "in_stock" => false
    ],
    //Beginning tablets//
    [
      "id" => "113",
      "name" => "lenovotablet0",
      "price" => "890.99",
      "image" => "assets/img/lenovotablet0.jpg",
      "imagefront" => "assets/img/lenovotablet0voorkant.jpg",
      "imageback" => "assets/img/lenovotablet0achterkant.jpg",
      "imageside" => "assets/img/lenovotablet0zijkant.jpg",
      "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
      "button" => "",
      "button2" => "",
      "in_stock" => true
      
    ],
    [
    "id" => "114",
    "name" => "lenovotablet1",
    "price" => "999.99",
    "image" => "assets/img/lenovotablet1.jpg",
    "imagefront" => "assets/img/lenovotablet1voorkant.jpg",
    "imageback" => "assets/img/lenovotablet1achterkant.jpg",
    "imageside" => "assets/img/lenovotablet1zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "115",
    "name" => "samsungtablet2",
    "price" => "1009.99",
    "image" => "assets/img/samsungtablet2.jpg",
    "imagefront" => "assets/img/samsungtablet2voorkant.jpg",
    "imageback" => "assets/img/samsungtablet2achterkant.jpg",
    "imageside" => "assets/img/samsungtablet2zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "116",
    "name" => "samsungtablet3",
    "price" => "1009.99",
    "image" => "assets/img/samsungtablet3.jpg",
    "imagefront" => "assets/img/samsungtablet3voorkant.jpg",
    "imageback" => "assets/img/samsungtablet3achterkant.jpg",
    "imageside" => "assets/img/samsungtablet3zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => false
  ],
  [//Beginning Ipads//
    "id" => "117",
    "name" => "appleipad0",
    "price" => "999.99",
    "image" => "assets/img/appleipad0.jpg",
    "imagefront" => "assets/img/appleipad0voorkant.jpg",
    "imageback" => "assets/img/appleipad0achterkant.jpg",
    "imageside" => "assets/img/appleipad0zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "118",
    "name" => "appleipad1",
    "price" => "1009.99",
    "image" => "assets/img/appleipad1.jpg",
    "imagefront" => "assets/img/appleipad1voorkant.jpg",
    "imageback" => "assets/img/appleipad1achterkant.jpg",
    "imageside" => "assets/img/appleipad1zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [//Beginning headsets//
    "id" => "119",
    "name" => "sonyheadset0",
    "price" => "1009.99",
    "image" => "assets/img/sonyheadset0.jpg",
    "imagefront" => "assets/img/sonyheadset0voorkant.jpg",
    "imageback" => "assets/img/sonyheadset0achterkant.jpg",
    "imageside" => "assets/img/sonyheadset0zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => false
  ],
  [
    "id" => "120",
    "name" => "sonyheadset1",
    "price" => "999.99",
    "image" => "assets/img/sonyheadset1.jpg",
    "imagefront" => "assets/img/sonyheadset1voorkant.jpg",
    "imageback" => "assets/img/sonyheadset1achterkant.jpg",
    "imageside" => "assets/img/sonyheadset1zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [//Beginning second part phones//
    "id" => "121",
    "name" => "motorola4",
    "price" => "1009.99",
    "image" => "assets/img/motorola4.jpg",
    "imagefront" => "assets/img/motorola4voorkant.jpg",
    "imageback" => "assets/img/motorola4achterkant.jpg",
    "imageside" => "assets/img/motorola4zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "122",
    "name" => "motorola5",
    "price" => "1009.99",
    "image" => "assets/img/motorola5.jpg",
    "imagefront" => "assets/img/motorola5voorkant.jpg",
    "imageback" => "assets/img/motorola5achterkant.jpg",
    "imageside" => "assets/img/motorola5zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => false
  ],
  [
    "id" => "123",
    "name" => "apple5",
    "price" => "999.99",
    "image" => "assets/img/apple5.jpg",
    "imagefront" => "assets/img/apple5voorkant.jpg",
    "imageback" => "assets/img/apple5achterkant.jpg",
    "imageside" => "assets/img/apple5zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "124",
    "name" => "apple6",
    "price" => "1009.99",
    "image" => "assets/img/apple6.jpg",
    "imagefront" => "assets/img/apple6voorkant.jpg",
    "imageback" => "assets/img/apple6achterkant.jpg",
    "imageside" => "assets/img/apple6zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "125",
    "name" => "apple7",
    "price" => "1009.99",
    "image" => "assets/img/apple7.jpg",
    "imagefront" => "assets/img/apple7voorkant.jpg",
    "imageback" => "assets/img/apple7achterkant.jpg",
    "imageside" => "assets/img/apple7zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => false
  ],
  [
    "id" => "126",
    "name" => "xiaomi8",
    "price" => "999.99",
    "image" => "assets/img/xiaomi8.jpg",
    "imagefront" => "assets/img/xiaomi8voorkant.jpg",
    "imageback" => "assets/img/xiaomi8achterkant.jpg",
    "imageside" => "assets/img/xiaomi8zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "127",
    "name" => "xiaomi9",
    "price" => "1009.99",
    "image" => "assets/img/xiaomi9.jpg",
    "imagefront" => "assets/img/xiaomi9voorkant.jpg",
    "imageback" => "assets/img/xiaomi9achterkant.jpg",
    "imageside" => "assets/img/xiaomi9zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "128",
    "name" => "nokia10",
    "price" => "1009.99",
    "image" => "assets/img/nokia10.jpg",
    "imagefront" => "assets/img/nokia10voorkant.jpg",
    "imageback" => "assets/img/nokia10achterkant.jpg",
    "imageside" => "assets/img/nokia10zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => false
  ],
  [
    "id" => "129",
    "name" => "nokia11",
    "price" => "999.99",
    "image" => "assets/img/nokia11.jpg",
    "imagefront" => "assets/img/nokia10voorkant.jpg",
    "imageback" => "assets/img/nokia10achterkant.jpg",
    "imageside" => "assets/img/nokia10zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "130",
    "name" => "nokia12",
    "price" => "1009.99",
    "image" => "assets/img/nokia12.jpg",
    "imagefront" => "assets/img/nokia12voorkant.jpg",
    "imageback" => "assets/img/nokia12achterkant.jpg",
    "imageside" => "assets/img/nokia12zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => true
  ],
  [
    "id" => "131",
    "name" => "sony13",
    "price" => "1009.99",
    "image" => "assets/img/sony13.jpg",
    "imagefront" => "assets/img/sony13voorkant.jpg",
    "imageback" => "assets/img/sony13achterkant.jpg",
    "imageside" => "assets/img/sony13zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => false
  ],
  [
    "id" => "132",
    "name" => "sony14",
    "price" => "1009.99",
    "image" => "assets/img/sony14.jpg",
    "imagefront" => "assets/img/sony14voorkant.jpg",
    "imageback" => "assets/img/sony14achterkant.jpg",
    "imageside" => "assets/img/sony14zijkant.jpg",
    "shop-icon" => "<span class='cart-icon material-symbols-outlined'>shopping_cart</span>",
    "button" => "",
    "button2" => "",
    "in_stock" => false
  ],

];
?>